name: 'Publish module'
description: 'Publish module'

inputs:
  templateFilePath:
    description: 'The path to the template file to publish'
    required: true
  componentTemplateSpecRGName:
    description: 'Required to publish to template spec. ResourceGroup of the template spec to publish to'
    required: false
  componentTemplateSpecRGLocation:
    description: 'Required to publish to template spec. Location of the template spec resource group'
    required: false
  componentTemplateSpecName:
    description: 'Required to publish to template spec. Name of the template spec to publish to'
    required: false
  componentTemplateSpecDescription:
    description: 'Required to publish to template spec. Description of the template spec to publish to'
    required: false
  publishToTemplateSpec:
    description: 'Flag to indicate whether or not to publish to template specs'
    default: 'false'
    required: false
  componentBicepRegistryName:
    description: 'Required to publish to private bicep registry. ResourceGroup of the container registry to publish to'
    required: false
  componentBicepRegistryRGName:
    description: 'Required to publish to private bicep registry. Location of the container registry resource group'
    required: false
  publishToPrivateBicepRegistry:
    description: 'Flag to indicate whether or not to publish to the private bicep registry'
    default: 'false'
    required: false
  versioningOption:
    description: 'The mode to handle the version increments [major|minor|patch|custom].'
    default: 'patch'
    required: false
  customVersion:
    description: 'The version to enforce if [versioningOption] is set to [custom]'
    default: '0.0.1'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent & login'
      shell: pwsh
      run: |
        # Load used functions
        . ".github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1"
        # Set agent up
        Set-EnvironmentOnAgent

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: 'Publish module to template spec'
      shell: pwsh
      # if: ${{ inputs.publishToTemplateSpec == 'true' }}
      run: |
        # Workaround until composite actions support conditions
        # Once available, remove this if and enable the step condition
        if('${{ inputs.publishToTemplateSpec }}' -eq 'true') {

          # Load used functions
          . "$env:GITHUB_ACTION_PATH/scripts/Publish-ModuleToTemplateSpec.ps1"

          $functionInput = @{
            templateFilePath                      = '${{ inputs.templateFilePath }}'
            componentTemplateSpecName             = '${{ inputs.componentTemplateSpecName }}'
            componentTemplateSpecRGName           = '${{ inputs.componentTemplateSpecRGName }}'
            componentTemplateSpecRGLocation       = '${{ inputs.componentTemplateSpecRGLocation }}'
            componentTemplateSpecDescription      = '${{ inputs.componentTemplateSpecDescription }}'
            customVersion                         = '${{ inputs.customVersion }}'
            versioningOption                      = '${{ inputs.versioningOption }}'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Publish-ModuleToTemplateSpec @functionInput -Verbose
        } else {
          Write-Output "Pipeline is configured to not publish to TemplateSpecs"
        }

    - name: 'Publish module to private bicep registry'
      shell: pwsh
      # if: ${{ inputs.publishToPrivateBicepRegistry == 'true' }}
      run: |
        # Workaround until composite actions support conditions
        # Once available, remove this if and enable the step condition
        if('${{ inputs.publishToPrivateBicepRegistry }}' -eq 'true') {

          # Load used functions
          . "$env:GITHUB_ACTION_PATH/scripts/Publish-ModuleToPrivateBicepRegistry.ps1"

          $templateFilePath = Join-Path "$env:GITHUB_WORKSPACE" "${{ inputs.templateFilePath }}"

          # Extracts Microsoft.KeyVault/vaults from e.g. C:\arm\Microsoft.KeyVault\vaults\deploy.bicep
          $moduleIdentifier = (Split-Path $templateFilePath -Parent).Replace('\','/').Split('/arm/')[1]

          $functionInput = @{
            moduleIdentifier             = $moduleIdentifier
            templateFilePath             = $templateFilePath
            componentBicepRegistryName   = '${{ inputs.componentBicepRegistryName }}'
            componentBicepRegistryRGName = '${{ inputs.componentBicepRegistryRGName }}'
            customVersion                = '${{ inputs.customVersion }}'
            versioningOption             = '${{ inputs.versioningOption }}'
          }

          Write-Verbose "Invoke task with" -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Publish-ModuleToPrivateBicepRegistry @functionInput -Verbose
        } else {
          Write-Output "Pipeline is configured to not publish to TemplateSpecs"
        }
