name: 'Publish module'
description: 'Publish module'

inputs:
  templateFilePath:
    description: 'The path to the template file to publish'
    required: true
  componentTemplateSpecRGName:
    description: 'Required to publish to template spec. ResourceGroup of the template spec to publish to'
    required: false
  componentTemplateSpecRGLocation:
    description: 'Required to publish to template spec. Location of the template spec resource group'
    required: false
  componentTemplateSpecName:
    description: 'Required to publish to template spec. Name of the template spec to publish to'
    required: false
  componentTemplateSpecDescription:
    description: 'Required to publish to template spec. Description of the template spec to publish to'
    required: false
  publishToTemplateSpec:
    description: 'Flag to indicate whether or not to publish to template specs'
    default: 'false'
    required: false
  versioningOption:
    description: 'The mode to handle the version increments [major|minor|patch|custom].'
    default: 'patch'
    required: false
  customVersion:
    description: 'The version to enforce if [versioningOption] is set to [custom]'
    default: '0.0.1'
    required: false

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}

    - name: "Publish module to template spec"
      shell: pwsh
      # if: ${{ inputs.publishToTemplateSpec == 'true' }}
      run: |
        # Load used functions
        . "$env:GITHUB_ACTION_PATH/scripts/Publish-ModuleToTemplateSpec.ps1"

        $functionInput = @{
          templateFilePath                      = '${{ inputs.templateFilePath }}'
          componentTemplateSpecName             = '${{ inputs.componentTemplateSpecName }}'
          componentTemplateSpecRGName           = '${{ inputs.componentTemplateSpecRGName }}'
          componentTemplateSpecRGLocation       = '${{ inputs.componentTemplateSpecRGLocation }}'
          componentTemplateSpecDescription      = '${{ inputs.componentTemplateSpecDescription }}'
          customVersion                         = '${{ inputs.customVersion }}'
          versioningOption                      = '${{ inputs.versioningOption }}'
        }

        Write-Verbose "Invoke task with" -Verbose
        $functionInput

        Publish-ModuleToTemplateSpec @functionInput -Verbose