name: 'Validate module'
description: 'Validate module'

inputs:
  templateFilePath:
    description: 'The path to the template file to use for testing & deployment'
    required: true
  parameterFilePath:
    description: 'The path to the parameter file to use for testing & deployment'
    required: true

runs:
  using: "composite"
  steps:
  - name: "Validate module"
    shell: pwsh
    run: |
      # Load used functions
      . "$env:GITHUB_ACTION_PATH/scripts/<ScriptName>.ps1"

      $setupInputParameters = @{
      }
      <FunctionName> @setupInputParameters