name: 'Insights - Components'

parameters:
  - name: removeDeployment
    displayName: Remove deployed module
    type: boolean
    default: true
  - name: prerelease
    displayName: Publish prerelease module
    type: boolean
    default: false

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - '/.azuredevops/modulePipelines/ms.insights.components.yml'
      - '/.azuredevops/pipelineTemplates/module.*.yml'
      - '/arm/Microsoft.Insights/components/*'
    exclude:
      - '/**/*.md'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: modulePath
    value: '/arm/Microsoft.Insights/components'

stages:
  - stage: Validation
    displayName: Pester tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.validate.yml

  - stage: Deployment
    displayName: Deployment tests
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.deploy.yml
        parameters:
          removeDeployment: '${{ parameters.removeDeployment }}'
          deploymentBlocks:
            - path: $(modulePath)/.parameters/parameters.json

  - stage: Publishing
    displayName: Publish module
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.publish.yml'
