parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'

  # Logic-related parameters
  modulePath: '$(modulePath)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job: getParameterFilePaths
    displayName: Get deployment test file paths
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - task: PowerShell@2
        displayName: 'Get parameter files'
        name: getParameterFilePathsTask
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' 'utilities' 'pipelines' 'sharedScripts' 'Get-DeploymentTestFileList.ps1')

            $functionInput = @{
              ModulePath = Join-Path '$(System.DefaultWorkingDirectory)' '$(modulePath)'
            }

            Write-Verbose "Invoke task with" -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            # Set agent up
            $deploymentTestPaths = Get-DeploymentTestFileList @functionInput -Verbose

            $testTable = @{}
            foreach($parameterFilePath in $deploymentTestPaths) {
              $parameterFileName = Split-Path $parameterFilePath -Leaf
              $testTable[$parameterFileName] = @{
                parameterFilePath = $parameterFilePath
              }
            }

            $deploymentTestPathsOutput = $testTable | ConvertTo-Json -Compress
            Write-Host ('##vso[task.setVariable variable=parameterTests;isOutput=true]{0}' -f ($testTable | ConvertTo-Json -Compress))
            Write-Verbose "Parameter files: $deploymentTestPathsOutput" -Verbose
