parameters:
  # Pipeline-related parameters
  poolName: '$(poolName)'
  vmImage: '$(vmImage)'

  # Logic-related parameters
  modulePath: '$(modulePath)'
  psRuleFilterRegex: '(defaults|waf-aligned)'

##---------------------------------------------##
## TEMPLATE LOGIC                              ##
##---------------------------------------------##
jobs:
  - job: getModuleTestFiles
    displayName: Get deployment test file paths
    pool:
      ${{ if ne(parameters.vmImage, '') }}:
        vmImage: ${{ parameters.vmImage }}
      ${{ if ne(parameters.poolName, '') }}:
        name: ${{ parameters.poolName }}
    steps:
      - task: PowerShell@2
        displayName: 'Get parameter files'
        name: getModuleTestFilesTask
        inputs:
          targetType: inline
          pwsh: true
          script: |
            ## ======= ##
            ##   All   ##
            ## ======= ##

            Write-Output '::group::Get all test files'

            # Get the list of parameter file paths
            $moduleFolderPath = Join-Path '$(System.DefaultWorkingDirectory)' '${{ parameters.modulePath }}'

            $testFilePaths = (Get-ChildItem -Path $moduleFolderPath -Recurse -Filter 'main.test.bicep').FullName | Sort-Object
            $testFilePaths = $testFilePaths | ForEach-Object {
              $_.Replace($moduleFolderPath, '').Trim('\').Trim('/')
            }

            Write-Verbose 'Found all module test files' -Verbose
            $testFilePaths | ForEach-Object { Write-Verbose "- [$_]" -Verbose }

            # Output values to be accessed by next jobs
            $deployCompressedOutput = $testFilePaths | ForEach-Object {
              @{
                path = $_
                name = Split-Path (Split-Path $_) -Leaf
              }
            } | ConvertTo-Json -Compress

            # Output values to be accessed by next jobs
            if($deployCompressedOutput -notmatch "\[.*\]") {
              $deployCompressedOutput = "[$deployCompressedOutput]"
            }

            Write-Verbose "Publishing output: $deployCompressedOutput" -Verbose
            Write-Host ('##vso[task.setVariable variable=moduleTestFilePaths;isOutput=true]{0}' -f $deployCompressedOutput)

            Write-Output '::endgroup::'

            ## =========== ##
            ##   PS-Rule   ##
            ## =========== ##

            Write-Output '::group::Get PSRule test files'
            $psRuleTestFilePaths = $testFilePaths | Where-Object { $_ -match '${{ parameters.psRuleFilterRegex }}' }

            Write-Verbose 'Found PSRule module test files' -Verbose
            $psRuleTestFilePaths | ForEach-Object { Write-Verbose "- [$_]" -Verbose }

            $psRuleCompressedOutput = $psRuleTestFilePaths | ForEach-Object {
              @{
                path = $_
                name = Split-Path (Split-Path $_) -Leaf
              }
            } | ConvertTo-Json -Compress

            # Output values to be accessed by next jobs
            if($psRuleCompressedOutput -notmatch "\[.*\]") {
              $psRuleCompressedOutput = "[$psRuleCompressedOutput]"
            }

            Write-Host ('##vso[task.setVariable variable=psRuleModuleTestFilePaths;isOutput=true]{0}' -f $psRuleCompressedOutput)
            Write-Verbose "PS Rule publishing output: $psRuleCompressedOutput" -Verbose

            Write-Output '::endgroup::'
