parameters:
  staticValidation: true
  deploymentValidation: true
  removeDeployment: true
  prerelease: false
  templateFilePath: ''
  defaultJobTimeoutInMinutes: 120

stages:
  - stage: validation
    displayName: Static validation
    condition: and(succeeded(), eq('${{ parameters.staticValidation }}', 'true'))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModulePester.yml

  - stage: deployment
    displayName: Deployment validation
    condition: and(succeeded(), eq('${{ parameters.deploymentValidation }}', 'true'))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.validateModuleDeployment.yml
        parameters:
          templateFilePath: '$(modulePath)/deploy.bicep'
          removeDeployment: '${{ parameters.removeDeployment }}'
          defaultJobTimeoutInMinutes: ${{ parameters.defaultJobTimeoutInMinutes }}

  - stage: Publishing
    dependsOn:
      - validation
      - deployment
    displayName: Publish module
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq('${{ parameters.prerelease }}', 'true')))
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.publishModule.yml
