name: '.Platform - Remove Deployments'

schedules:
- cron: "0 0 * * *"
  displayName: Nightly run
  branches:
    include:
    - main

pr: none

variables:
  - template: '../../settings.yml'
  - group: 'PLATFORM_VARIABLES'

jobs:
  - job: Update_module_tables
    pool:
      ${{ if eq(variables['vmImage'], '') }}:
        name: $(poolName)
      ${{ if eq(variables['poolName'], '') }}:
        vmImage: $(vmImage)
    steps:
      - checkout: self
      - task: PowerShell@2
        displayName: 'Setup agent for deployment'
        inputs:
          targetType: inline
          pwsh: true
          script: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

            # Define PS modules to install on the runner
            $Modules = @(
                @{ Name = 'Az.Accounts' }
            )

            # Set agent up
            Set-EnvironmentOnAgent -PSModules $Modules
      - task: AzurePowerShell@5
        displayName: 'Replace tokens in template file via connection [$(serviceConnection)]'
        inputs:
          azureSubscription: '$(serviceConnection)'
          ScriptType: InlineScript
          pwsh: true
          inline: |
            # Load used functions
            . (Join-Path '$(System.DefaultWorkingDirectory)' 'utilities' 'pipelines' 'deploymentRemoval' 'Clear-SubscriptionDeployment.ps1')

            $functionInput = @{
              SubscriptionId = '$(ARM_SUBSCRIPTION_ID)'
              Verbose        = $true
            }

            Write-Verbose 'Invoke task with' -Verbose
            Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

            Clear-SubscriptionDeployment @functionInput
