name: '.Platform - Dependencies'

# trigger:
#   batch: true
#   branches:
#     include:
#       - main
#   paths:
#     include:
#       - '.azuredevops/pipelineTemplates/module.jobs.deploy.yml'
#       - '.azuredevops/platformPipelines/platform.dependencies.yml'
#       - 'utilities/pipelines/dependencies/**'

variables:
  - template: '/.azuredevops/pipelineVariables/global.variables.yml'
  - group: 'PLATFORM_VARIABLES'
  - name: dependencyPath
    value: 'utilities/pipelines/dependencies'
  - name: modulesPath
    value: 'arm'

stages:
  - stage: deploy_rg
    displayName: Deploy resource group
    variables:
      templateFilePath: $(modulesPath)/Microsoft.Resources/resourceGroups/deploy.bicep
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.deploy.yml
        parameters:
          deploymentBlocks:
            - path: $(dependencyPath)/Microsoft.Resources/resourceGroups/parameters/artifacts.parameters.json
              templateFilePath: $(templateFilePath)
              displayName: Artifacts Resource Group
            - path: $(dependencyPath)/Microsoft.Resources/resourceGroups/parameters/validation.parameters.json
              templateFilePath: $(templateFilePath)
              displayName: Validation Resource Group

  - stage: deploy_msi
    displayName: Deploy user assigned identity
    variables:
      templateFilePath: $(modulesPath)/Microsoft.ManagedIdentity/userAssignedIdentities/deploy.bicep
    jobs:
      - template: /.azuredevops/pipelineTemplates/module.jobs.deploy.yml
        parameters:
          deploymentBlocks:
            - path: $(dependencyPath)/Microsoft.Resources/resourceGroups/parameters/parameters.json
              templateFilePath: $(templateFilePath)
              displayName: User Assigned Identity
    dependsOn:
      - deploy_rg
