name: 'Solutions - Monitor'

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - solutions/CoreInfra/Platform/Monitor*

variables:
  # - template: /settings.yml
  - template: pipeline.variables.yml

stages:
  - stage:
    displayName: WhatIf
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/parameters.json'
          whatif: true
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/logAnalytics/parameters.json'
          whatif: true
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/actionGroups/parameters.json'
          whatif: true
          checkoutRepositories:
            - self

  - stage:
    displayName: Deploy
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: logAnalytics
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/logAnalytics/parameters.json'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: actionGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Platform/Monitor/PipelineOrchestrated/actionGroups/parameters.json'
          checkoutRepositories:
            - self
