name: armDeployment

description: "Triggers an ARM Template Deployment at Different Scopes"

inputs:
  # Required Parameters
  templateFile:
    description: "Path to the ARM Template File (Module)"
    required: true

  templateParametersFile:
    description: "Directory for ARM Template Parameter Files or Direct Path to ARM Template Parameter File"
    required: true

  location:
    description: "The location for the deployment. Applies to all scopes"
    required: true

  # Optional Parameters
  tags:
    description: "Provide an Object of Key Value Pairs in the form of String that are passed to the script as Tags"
    required: false
    default: "$null"

  resourceGroupName:
    description: "Name of the Resource Group if targeting resourceGroup"
    required: false
    default: "$null"

  subscriptionId:
    description: "The ID the Azure Subscription if targeting resourceGroup or subscription"
    required: false
    default: "$null"

  managementGroupId:
    description: "The ID the Azure Management Group if targeting managementGroup"
    required: false
    default: "$null"

runs:
  using: "composite"
  steps:
    - name: "${{ inputs.scope }}_deployment"
      uses: azure/powershell@v1
      with:
        azPSVersion: "6.4.0"
        inlineScript: |
          $CommonParameters = @{
            templateFile            = "${{ inputs.templateFile }}"
            templateParametersFile  = "${{ inputs.templateParametersFile }}"
            location                = "${{ inputs.location }}"
            tags                    = "${{ inputs.tags }}"
            resourceGroupName       = "${{ inputs.resourceGroupName }}"
            subscriptionId          = "${{ inputs.subscriptionId }}"
            managementGroupId       = "${{ inputs.managementGroupId }}"
          }

          ${{ github.action_path }}/New-ArmDeployment.ps1 @commonParameters -Verbose
