name: 'Deploy module'
description: 'Deploy module'

inputs:
  templateFilePath:
    description: 'The path to the template file to use for deployment'
    required: true
  parameterFilePath:
    description: 'The path to the parameter file to use for deployment'
    required: true
  location:
    description: 'The location to use for deployment'
    required: true
  resourceGroupName:
    description: 'The resource group to deploy to'
    required: false
  subscriptionId:
    description: 'The subscriptionId to deploy to'
    required: false
  managementGroupId:
    description: 'The managementGroupId to deploy to'
    required: false
  removeDeployment:
    description: 'Set "true" to set module up for removal'
    default: 'true'
    required: false
  relativePathOfRemovalScript:
    description: 'The relative path from root to the script that removes the service'
    required: false
    default: 'utilities/pipelines/resourceRemoval/Remove-DeployedModule.ps1'

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent'
      shell: pwsh
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'sharedScripts' 'Set-EnvironmentOnAgent.ps1')

        # Set agent up
        Set-EnvironmentOnAgent

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: 'Replace Parameter File Tokens [${{ inputs.parameterFilePath }}] '
      shell: pwsh
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'tokensReplacement' 'Convert-TokensInParameterFile.ps1')

        # Load Settings File
        $Settings = Get-Content -Path "settings.json" | ConvertFrom-Json
        # Initialize Default Parameter File Tokens
        $DefaultParameterFileTokens = @(
            @{ Name = 'resourceGroupName'; Value = '${{ inputs.resourceGroupName }}' }
            @{ Name = 'subscriptionId'; Value = '${{ inputs.subscriptionId }}' }
            @{ Name = 'managementGroupId'; Value = '${{ inputs.managementGroupId }}' }
            @{ Name = "tenantId"; Value = '${{ env.ARM_TENANT_ID }}' }
            @{ Name = "deploymentSpId"; Value = '${{ env.DEPLOYMENT_SP_ID }}' }
            @{ Name = "platformKeyVault"; Value = '${{ env.PLATFORM_KEYVAULT }}' }
        ) | ForEach-Object { [PSCustomObject]$PSItem }

        # Construct Token Function Input
        $ConvertTokensInputs = @{
            ParameterFilePath                 = '${{ inputs.parameterFilePath }}'
            DefaultParameterFileTokens        = $DefaultParameterFileTokens
            LocalCustomParameterFileTokens    = $Settings.parameterFileTokens.localTokens.tokens
            TokenPrefix                       = $Settings.parameterFileTokens.tokenPrefix
            TokenSuffix                       = $Settings.parameterFileTokens.tokenSuffix
        }
        # Add Remote Custom Parameter File Tokens
        if ('${{ env.PLATFORM_KEYVAULT }}' -and '${{ inputs.subscriptionId }}') {
            $ConvertTokensInputs += @{
                TokensKeyVaultName                 = '${{ env.PLATFORM_KEYVAULT }}'
                TokensKeyVaultSubscriptionId       = '${{ inputs.subscriptionId }}'
                TokensKeyVaultSecretNamePrefix     = $Settings.parameterFileTokens.remoteTokens.keyVaultSecretNamePrefix
            }
        }
        # Invoke Token Replacement Functionality
        $null = Convert-TokensInParameterFile @ConvertTokensInputs -Verbose

    - name: 'Deploy [${{ inputs.templateFilePath }}] with parameters [${{ inputs.parameterFilePath }}]'
      shell: pwsh
      id: deploy_step
      run: |
        # Load used functions
        . (Join-Path $env:GITHUB_WORKSPACE 'utilities' 'pipelines' 'resourceDeployment' 'New-ModuleDeployment.ps1')

        $functionInput = @{
          moduleName         = Split-Path '${{ inputs.templateFilePath }}' -Parent
          templateFilePath   = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
          parameterFilePath  = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.parameterFilePath }}'
          location           = '${{ inputs.location }}'
          resourceGroupName  = '${{ inputs.resourceGroupName }}'
          subscriptionId     = '${{ inputs.subscriptionId }}'
          managementGroupId  = '${{ inputs.managementGroupId }}'
          removeDeployment   = [System.Convert]::ToBoolean('${{ inputs.removeDeployment }}')
          doNotThrow         = $true
        }

        Write-Verbose "Invoke task with" -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        # Invoke deployment
        $res = New-ModuleDeployment @functionInput -Verbose

        # Get deployment name
        if($res -is [hashtable]) {
          $deploymentName = $res['DeploymentName']
        } elseif($res -is [string]) {
          $deploymentName = $res
        } else {
          throw ("Output-Type of New-ModuleDeployment invocation has invalid type [{0}]" -f $res.GetType())
        }
        Write-Output ('::set-output name=deploymentName::{0}' -f $deploymentName)

        if($res -is [hashtable]) {
          # Happens only if there is an exception
          throw $res['Exception']
        }

    - name: 'Remove [${{ inputs.templateFilePath }}] from parameters [${{ inputs.parameterFilePath }}]'
      shell: pwsh
      if: always()
      run: |
        if('${{ inputs.removeDeployment }}' -eq 'true') {
          # Load used functions
          $functionPath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.relativePathOfRemovalScript }}'
          . $functionPath

          $functionInput = @{
              resourceGroupName = '${{ inputs.resourceGroupName }}'
              verbose           = $true
          }
          if(-not [String]::IsNullOrEmpty('${{ steps.deploy_step.outputs.deploymentName }}')) {
            Write-Verbose "Triggering removal with deployment name"
            $functionInput['deploymentName'] = '${{ steps.deploy_step.outputs.deploymentName }}'
            $functionInput['templateFilePath'] = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.templateFilePath }}'
          } else {
            $functionInput['moduleName'] = Split-Path '${{ inputs.templateFilePath }}' -Parent
          }

          Write-Verbose 'Invoke task with' -Verbose
          Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

          Invoke-Expression ('{0} @functionInput' -f (Split-Path $functionPath -LeafBase))
        }
