name: 'solutions-ne-spoke-rg'

parameters:
- name: whatif
  displayName: Validate template file via connection
  type: boolean
  default: true
- name: removeDeployment
  displayName: Remove resources post-deployment
  type: boolean
  default: true

pr: none

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - solutions/CoreInfra/Platform/HubNetwork*

variables:
  - template: pipeline.variables.yml

stages:
  - stage:
    displayName: WhatIf
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: networkSecurityGroups
          displayName: 'Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/networkSecurityGroups/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/routeTables/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: virtualNetworks
          displayName: 'Virtual Networks'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/virtualNetworks/parameters.json'
          whatif: '${{ parameters.whatif }}'
          checkoutRepositories:
            - self

  - stage:
    displayName: Deployment
    jobs:
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: resourceGroups
          displayName: 'Resource Group'
          modulePath: '/modules/Microsoft.Resources/resourceGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/parameters.json'
          removeDeployment: '${{ parameters.removeDeployment }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: networkSecurityGroups
          displayName: 'Network Security Groups'
          modulePath: '/modules/Microsoft.Network/networkSecurityGroups/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/networkSecurityGroups/parameters.json'
          removeDeployment: '${{ parameters.removeDeployment }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: routeTables
          displayName: 'Route Tables'
          modulePath: '/modules/Microsoft.Network/routeTables/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/routeTables/parameters.json'
          removeDeployment: '${{ parameters.removeDeployment }}'
          checkoutRepositories:
            - self
      - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
        parameters:
          jobName: virtualNetworks
          displayName: 'Virtual Networks'
          modulePath: '/modules/Microsoft.Network/virtualNetworks/deploy.bicep'
          moduleTestFilePath: '/solutions/CoreInfra/Spoke/PipelineOrchestrated/virtualNetworks/parameters.json'
          removeDeployment: '${{ parameters.removeDeployment }}'
          checkoutRepositories:
            - self
          dependsOn:
            - networkSecurityGroups
            - routeTables

  - stage: Removal
    dependsOn: Deployment
    condition: and(succeededOrFailed(), eq( '${{ parameters.removeDeployment }}', 'true'))
    jobs:
    - template: /.azuredevops/pipelineTemplates/jobs.solutionDeployment.yml
