name: 'Remove module'
description: 'Remove module'

inputs:
  moduleName:
    description: 'The name of the module to remove'
    required: true
  templateFilePath:
    description: 'The path to the template file set for removal. Used to determine the type of resource.'
    required: true
  resourceGroupName:
    description: 'The resource group the module is deployed into'
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Remove module"
      shell: pwsh
      run: |
        # Load used functions
        . "$env:GITHUB_ACTION_PATH/scripts/Remove-DeployedModule.ps1"

        $functionInput = @{
          moduleName        = '${{ inputs.moduleName }}'
          resourceGroupName = '${{ inputs.resourceGroupName }}'
          templateFilePath  = '${{ inputs.templateFilePath }}'
        }

        Write-Verbose "Invoke task with" -Verbose
        $functionInput | Format-Table -AutoSize

        Remove-DeployedModule @functionInput -Verbose