name: 'Remove module'
description: 'Remove module'

inputs:
  moduleName:
    description: 'The name of the module to remove'
    required: true
  templateFilePath:
    description: 'The path to the template file set for removal. Used to determine the type of resource.'
    required: true
  resourceGroupName:
    description: 'The resource group the module is deployed into'
    required: false
  relativePathOfRemovalScript:
    description: 'The relative path from root to the script that removes the service'
    required: false
    default: 'utilities/resourceRemoval/Remove-DeployedModule.ps1'

runs:
  using: 'composite'
  steps:
    - name: 'Setup agent & login'
      shell: pwsh
      run: |
        # Load used functions
        . ".github/actions/sharedScripts/Set-EnvironmentOnAgent.ps1"
        # Set agent up
        Set-EnvironmentOnAgent

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: 'Remove module'
      shell: pwsh
      run: |
        # Load used functions
        $functionPath = Join-Path $env:GITHUB_WORKSPACE '${{ inputs.relativePathOfRemovalScript }}'
        . $functionPath

        $functionInput = @{
            moduleName        = '${{ inputs.moduleName }}'
            resourceGroupName = '${{ inputs.resourceGroupName }}'
            verbose           = $true
        }

        Write-Verbose 'Invoke task with' -Verbose
        Write-Verbose ($functionInput | ConvertTo-Json | Out-String) -Verbose

        Invoke-Expression ('{0} @functionInput' -f (Split-Path $functionPath -LeafBase))
