name: 'Remove module'
description: 'Remove module'

inputs:
  moduleName:
    description: 'The name of the module to remove'
    required: true
  templateFilePath:
    description: 'The path to the template file set for removal. Used to determine the type of resource.'
    required: true
  resourceGroupName:
    description: 'The resource group the module is deployed into'
    required: true

runs:
  using: "composite"
  steps:
  - name: "Setup agent & login"
    shell: pwsh
    run: |
      # Load used functions
      . "$env:GITHUB_ACTION_PATH/scripts/Set-AgentUp.ps1"

      $setupInputParameters = @{
        clientID       = $env:ARM_CLIENT_ID
        clientSecret   = ConvertTo-SecureString -String $env:ARM_CLIENT_SECRET -AsPlainText -Force
        tenantId       = $env:ARM_TENANT_ID
        subscriptionId = $env:ARM_SUBSCRIPTION_ID
      }
      Set-AgentUp @setupInputParameters

  - name: "Remove module"
    shell: pwsh
    run: |
      # Load used functions
      . "$env:GITHUB_ACTION_PATH/scripts/Remove-DeployedModule.ps1"

      $setupInputParameters = @{
        moduleName        = '${{ inputs.moduleName }}'
        resourceGroupName = '${{ inputs.resourceGroupName }}'
        templateFilePath  = '${{ inputs.templateFilePath }}'
      }

      Write-Verbose "Invoke task with" -Verbose
      $functionInput | Format-Table -AutoSize

      Remove-DeployedModule @setupInputParameters -Verbose