name: 'Execute individual module tests'
description: 'Execute individual module tests (if any)'

inputs:
  modulePath:
    description: 'The path to the module folder'
    required: true
  moduleName:
    description: 'The name of the module to process'
    required: true

runs:
  using: "composite"
  steps:
  # [Module Pester Test] task(s)
  #-----------------------------
  - name: "Run [${{ inputs.moduleName }}] tests via (Pester)"
    shell: pwsh
    run: |
      # --------------------- #
      # INVOKE PESTER TEST(S) #
      # --------------------- #
      Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.3.0

      Invoke-Pester -Configuration @{
        Run        = @{
          Path = "${{ inputs.modulePath }}/Tests/*.tests.ps1"
        }
        TestResult = @{
          TestSuiteName = 'Module Tests'
          OutputPath    = 'module-testResults.xml'
          OutputFormat  = 'NUnitXml'
          Enabled       = $true
        }
        Output     = @{
          Verbosity = 'Detailed'
        }
      }

  # - task: PublishTestResults@2
  #   displayName: Publish Test Results
  #   inputs:
  #     testRunTitle: "Module Tests"
  #     testResultsFormat: NUnit
  #     testResultsFiles: module-testResults.xml
  #     failTaskOnFailedTests: false
  #   continueOnError: false
  #   condition: succeededOrFailed()
