name: 'Execute individual module tests'
description: 'Execute individual module tests (if any)'

inputs:
  modulePath:
    description: 'The path to the module folder'
    required: true
  moduleName:
    description: 'The name of the module to process'
    required: true

runs:
  using: "composite"
  steps:
    # [Module Pester Test] task(s)
    #-----------------------------
    - name: "Run [${{ inputs.moduleName }}] tests via (Pester)"
      shell: pwsh
      run: |
        # --------------------- #
        # INVOKE PESTER TEST(S) #
        # --------------------- #
        Install-Module Pester -Force -ErrorAction Stop -RequiredVersion 5.3.0

        Invoke-Pester -Configuration @{
          Run        = @{
            Path = "${{ inputs.modulePath }}/tests/*.tests.ps1"
          }
          TestResult = @{
            TestSuiteName = 'Module Tests'
            OutputPath    = 'module-testResults.xml'
            OutputFormat  = 'JUnitXml'
            Enabled       = $true
          }
          Output     = @{
            Verbosity = 'Detailed'
          }
        }
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      # if: always()
      with:
        files: module-testResults.xml