name: 'Network: VirtualNetworks'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove deployed module'
        required: false
        default: true
      prerelease:
        type: boolean
        description: 'Publish prerelease module'
        required: false
        default: false
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ms.network.virtualnetworks.yml'
      - 'modules/Microsoft.Network/virtualNetworks/**'
      - 'utilities/pipelines/**'
      - '!utilities/pipelines/deploymentRemoval/**'
      - '!*/**/readme.md'

env:
  variablesPath: 'settings.yml'
  modulePath: 'modules/Microsoft.Network/virtualNetworks'
  workflowPath: '.github/workflows/ms.network.virtualnetworks.yml'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
  ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
  TOKEN_NAMEPREFIX: '${{ secrets.TOKEN_NAMEPREFIX }}'

concurrency:
  group: ${{ github.workflow }}

jobs:
  ###########################
  #   Initialize pipeline   #
  ###########################
  job_initialize_pipeline:
    runs-on: ubuntu-20.04
    name: 'Initialize pipeline'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set input parameters to output variables'
        id: get-workflow-param
        uses: ./.github/actions/templates/getWorkflowInput
        with:
          workflowPath: '${{ env.workflowPath}}'
      - name: 'Get parameter file paths'
        id: get-module-test-file-paths
        uses: ./.github/actions/templates/getModuleTestFiles
        with:
          modulePath: '${{ env.modulePath }}'
    outputs:
      removeDeployment: '${{ steps.get-workflow-param.outputs.removeDeployment }}'
      versioningOption: '${{ steps.get-workflow-param.outputs.versioningOption }}'
      customVersion: '${{ steps.get-workflow-param.outputs.customVersion }}'
      modulePath: '${{ env.modulePath}}'

  ##############################
  #   Call reusable workflow   #
  ##############################
  call-workflow-passing-data:
    name: 'Template'
    needs:
    - job_set_workflow_param
    uses: eriqua/ResourceModules/.github/workflows/template.module.yml@main
    with:
      modulePath: '${{ needs.job_set_workflow_param.outputs.modulePath }}'
      removeDeployment: '${{ needs.job_set_workflow_param.outputs.removeDeployment }}'
      versioningOption: '${{ needs.job_set_workflow_param.outputs.versioningOption }}'
      customVersion: '${{ needs.job_set_workflow_param.outputs.customVersion }}'
    secrets:
      AZURE_CREDENTIALS: '${{ secrets.AZURE_CREDENTIALS }}'
      ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
      ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      DEPLOYMENT_SP_ID: '${{ secrets.DEPLOYMENT_SP_ID }}'
