name: 'Resources: ResourceGroups'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove deployed module'
        required: false
        default: 'true'
      versioningOption:
        type: choice
        description: 'The mode to handle the version increments [major|minor|patch]'
        required: false
        default: 'patch'
        options:
          - major
          - minor
          - patch
      customVersion:
        description: 'Custom version to apply. Used only if higher than latest'
        required: false
        default: '0.0.1'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ms.resources.resourcegroups.yml'
      - 'arm/Microsoft.Resources/resourceGroups/**'
      - '.github/actions/templates/**'
      - '.github/workflows/template.module.yml'
      - '!*/**/readme.md'
      - 'utilities/pipelines/**'
      - '!utilities/pipelines/dependencies/**'

env:
  modulePath: 'arm/Microsoft.Resources/resourceGroups'
  workflowPath: '.github/workflows/ms.resources.resourcegroups.yml'
  # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  # ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  # ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
  # ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
  # DEPLOYMENT_SP_ID: '${{ secrets.DEPLOYMENT_SP_ID }}'

jobs:
  # ############################
  # #   Set input parameters   #
  # ############################
  # job_set_workflow_param:
  #   runs-on: ubuntu-20.04
  #   name: 'Set input parameters to output variables'
  #   steps:
  #     - name: 'Checkout'
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: 'Set input parameters'
  #       id: get-workflow-param
  #       uses: ./.github/actions/templates/getWorkflowInput
  #       with:
  #         workflowPath: '${{ env.workflowPath}}'
  #   outputs:
  #     removeDeployment: ${{ steps.get-workflow-param.outputs.removeDeployment }}
  #     versioningOption: ${{ steps.get-workflow-param.outputs.versioningOption }}
  #     customVersion: ${{ steps.get-workflow-param.outputs.customVersion }}

  # call-workflow-passing-data:
  #   needs:
  #   - job_set_workflow_param
  #   uses: ./.github/workflows/template.module.yml@main
  #   with:
  #     modulePath: '${{ env.modulePath}}'
  #     removeDeployment: '${{ needs.job_set_workflow_param.outputs.removeDeployment }}'
  #     versioningOption: '${{ needs.job_set_workflow_param.outputs.versioningOption }}'
  #     customVersion: '${{ needs.job_set_workflow_param.outputs.customVersion }}'

  call-workflow-passing-data:
    uses: eriqua/ResourceModules/.github/workflows/template.module.yml@main
    with:
      modulePath: 'arm/Microsoft.Resources/resourceGroups'
      removeDeployment: 'true'
      versioningOption: 'patch'
      customVersion: '0.0.1'
      DEPLOYMENT_SP_ID: 'example'
