name: 'Resources: ResourceGroups'

on:
  workflow_dispatch:
    inputs:
      removeDeployment:
        type: boolean
        description: 'Remove deployed module'
        required: false
        default: true
      prerelease:
        type: boolean
        description: 'Publish prerelease module'
        required: false
        default: false
  push:
    branches:
      - main
      - reus-wkf-donotdelete
    paths:
      - '.github/workflows/ms.resources.resourcegroups.yml'
      - 'modules/Microsoft.Resources/resourceGroups/**'
      - 'utilities/pipelines/**'
      - '!utilities/pipelines/deploymentRemoval/**'
      - '!*/**/readme.md'

env:
  # variablesPath: 'settings.yml'
  modulePath: 'modules/Microsoft.Resources/resourceGroups'
  workflowPath: '.github/workflows/ms.resources.resourcegroups.yml'
  # AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  # ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
  # ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
  # ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
  # TOKEN_NAMEPREFIX: '${{ secrets.TOKEN_NAMEPREFIX }}'

concurrency:
  group: ${{ github.workflow }}

jobs:
  ###########################
  #   Initialize pipeline   #
  ###########################
  job_initialize_pipeline:
    runs-on: ubuntu-20.04
    name: 'Initialize pipeline'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set input parameters to output variables'
        id: get-workflow-param
        uses: ./.github/actions/templates/getWorkflowInput
        with:
          workflowPath: '${{ env.workflowPath}}'
      - name: 'Get parameter file paths'
        id: get-module-test-file-paths
        uses: ./.github/actions/templates/getModuleTestFiles
        with:
          modulePath: '${{ env.modulePath }}'
    outputs:
      removeDeployment: '${{ steps.get-workflow-param.outputs.removeDeployment }}'
      workflowInput: ${{ steps.get-workflow-param.outputs.workflowInput }}
      moduleTestFilePaths: ${{ steps.get-module-test-file-paths.outputs.moduleTestFilePaths }}
      modulePath: '${{ env.modulePath}}'


  ##############################
  #   Call reusable workflow   #
  ##############################
  call-workflow-passing-data:
    name: 'Template'
    needs:
    - job_initialize_pipeline
    # uses: eriqua/ResourceModules/.github/workflows/template.module.yml@main
    uses: ./.github/workflows/template.module.yml
    with:
      modulePath: '${{ needs.job_initialize_pipeline.outputs.modulePath}}'
      removeDeployment: '${{ (fromJson(needs.job_initialize_pipeline.outputs.workflowInput)).removeDeployment }}'
      moduleTestFilePaths: '${{ needs.job_initialize_pipeline.outputs.moduleTestFilePaths }}'
      # prerelease: false
    secrets:
      AZURE_CREDENTIALS: '${{ secrets.AZURE_CREDENTIALS }}'
      ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
      ARM_MGMTGROUP_ID: '${{ secrets.ARM_MGMTGROUP_ID }}'
      ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
      TOKEN_NAMEPREFIX: '${{ secrets.TOKEN_NAMEPREFIX }}'
