name: "Maintenance: ReadMe Modules"

on:
  workflow_dispatch: 

env:
  #moduleName: 'servers'

jobs:
  job_update_readme:
    runs-on: ubuntu-20.04
    name: "Update module tables"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Update general ReadMe"
        shell: pwsh
        run: |
          $workspacePath = $GITHUB_WORKSPACE
          $readMePath = Join-Path $workspacePath 'README.md'

          Write-Verbose "Processing path [$readMePath]" -Verbose
          

          # ModuleTableStartMarker
          # ModuleTableEndMarker

      - name: "Update module folder ReadMe"
        shell: pwsh
        run: |
          $workspacePath = $GITHUB_WORKSPACE
          $readMePath = Join-Path $workspacePath 'arm/README.md'